# Generated by Django 5.2.5 on 2025-09-09 06:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField()),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('thumbnail', models.URLField(blank=True, null=True)),
                ('category', models.CharField(choices=[('footwear', 'Footwear'), ('jersey', 'Jersey'), ('ball', 'Ball'), ('bottle', 'Bottle'), ('accessory', 'Accessory')], default='footwear')),
                ('is_featured', models.BooleanField(default=False)),
            ],
        ),
    ]
